config/routes.rb
Horairehockey::Application.routes.draw do

  root 'welcome#index'

     get 'fetchers' => 'fetcher#fetch_prices'

     resources :endroits
     resources :categs
     resources :equipes

end

app/models/categ.rb
class Categ < ActiveRecord::Base
end

app/models/endroit.rb
class Endroit < ActiveRecord::Base
end

app/models/equipe.rb
class Equipe < ActiveRecord::Base
  belongs_to :categ
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categs_controller.rb
class CategsController < ApplicationController
  before_action :set_categ, only: [:show, :edit, :update, :destroy]

  # GET /categs
  # GET /categs.json
  def index
    @categs = Categ.all
  end

  # GET /categs/1
  # GET /categs/1.json
  def show
  end

  # GET /categs/new
  def new
    @categ = Categ.new
  end

  # GET /categs/1/edit
  def edit
  end

  # POST /categs
  # POST /categs.json
  def create
    @categ = Categ.new(categ_params)

    respond_to do |format|
      if @categ.save
        format.html { redirect_to @categ, notice: 'Categ was successfully created.' }
        format.json { render action: 'show', status: :created, location: @categ }
      else
        format.html { render action: 'new' }
        format.json { render json: @categ.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categs/1
  # PATCH/PUT /categs/1.json
  def update
    respond_to do |format|
      if @categ.update(categ_params)
        format.html { redirect_to @categ, notice: 'Categ was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @categ.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categs/1
  # DELETE /categs/1.json
  def destroy
    @categ.destroy
    respond_to do |format|
      format.html { redirect_to categs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categ
      @categ = Categ.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categ_params
      params.require(:categ).permit(:name)
    end
end

app/controllers/endroits_controller.rb
class EndroitsController < ApplicationController
  before_action :set_endroit, only: [:show, :edit, :update, :destroy]

  # GET /endroits
  # GET /endroits.json
  def index
    @endroits = Endroit.all
  end

  # GET /endroits/1
  # GET /endroits/1.json
  def show
  end

  # GET /endroits/new
  def new
    @endroit = Endroit.new
  end

  # GET /endroits/1/edit
  def edit
  end

  # POST /endroits
  # POST /endroits.json
  def create
    @endroit = Endroit.new(endroit_params)

    respond_to do |format|
      if @endroit.save
        format.html { redirect_to @endroit, notice: 'Endroit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @endroit }
      else
        format.html { render action: 'new' }
        format.json { render json: @endroit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /endroits/1
  # PATCH/PUT /endroits/1.json
  def update
    respond_to do |format|
      if @endroit.update(endroit_params)
        format.html { redirect_to @endroit, notice: 'Endroit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @endroit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /endroits/1
  # DELETE /endroits/1.json
  def destroy
    @endroit.destroy
    respond_to do |format|
      format.html { redirect_to endroits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endroit
      @endroit = Endroit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endroit_params
      params.require(:endroit).permit(:name, :url)
    end
end

app/controllers/equipes_controller.rb
class EquipesController < ApplicationController
  before_action :set_equipe, only: [:show, :edit, :update, :destroy]

  # GET /equipes
  # GET /equipes.json
  def index
    @equipes = Equipe.all
    @categs = Categ.all
  end

  # GET /equipes/1
  # GET /equipes/1.json
  def show
    @categs = Categ.all
  end

  # GET /equipes/new
  def new
    @equipe = Equipe.new
    @categ = Categ.all
  end

  # GET /equipes/1/edit
  def edit
  end

  # POST /equipes
  # POST /equipes.json
  def create
    @equipe = Equipe.new(equipe_params)

    respond_to do |format|
      if @equipe.save
        format.html { redirect_to @equipe, notice: 'Equipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @equipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @equipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipes/1
  # PATCH/PUT /equipes/1.json
  def update
    respond_to do |format|
      if @equipe.update(equipe_params)
        format.html { redirect_to @equipe, notice: 'Equipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @equipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipes/1
  # DELETE /equipes/1.json
  def destroy
    @equipe.destroy
    respond_to do |format|
      format.html { redirect_to equipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipe
      @equipe = Equipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipe_params
      params.require(:equipe).permit(:name, :categ_id)
    end
end

app/controllers/fetcher_controller.rb
class FetcherController < ApplicationController
  def fetch_prices
    require 'nokogiri'
    require 'open-uri'

    url = "http://www.huskyco.com/php/newevents.php"
    @webpage = Nokogiri::HTML(open(url))
    @doc = "produit final"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categs_helper.rb
module CategsHelper
end

app/helpers/endroits_helper.rb
module EndroitsHelper
end

app/helpers/equipes_helper.rb
module EquipesHelper
end

app/helpers/fetcher_helper.rb
module FetcherHelper
end

app/views/categs/_form.html.erb
<%= form_for(@categ) do |f| %>
  <% if @categ.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categ.errors.count, "error") %> prohibited this categ from being saved:</h2>

      <ul>
      <% @categ.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categs/edit.html.erb
<h1>Editing categ</h1>

<%= render 'form' %>

<%= link_to 'Show', @categ %> |
<%= link_to 'Back', categs_path %>

app/views/categs/index.html.erb
<h1>Listing categs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categs.each do |categ| %>
      <tr>
        <td><%= categ.name %></td>
        <td><%= link_to 'Show', categ %></td>
        <td><%= link_to 'Edit', edit_categ_path(categ) %></td>
        <td><%= link_to 'Destroy', categ, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categ', new_categ_path %>

app/views/categs/new.html.erb
<h1>New categ</h1>

<%= render 'form' %>

<%= link_to 'Back', categs_path %>

app/views/categs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @categ.name %>
</p>

<%= link_to 'Edit', edit_categ_path(@categ) %> |
<%= link_to 'Back', categs_path %>

app/views/endroits/_form.html.erb
<%= form_for(@endroit) do |f| %>
  <% if @endroit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@endroit.errors.count, "error") %> prohibited this endroit from being saved:</h2>

      <ul>
      <% @endroit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/endroits/edit.html.erb
<h1>Editing endroit</h1>

<%= render 'form' %>

<%= link_to 'Show', @endroit %> |
<%= link_to 'Back', endroits_path %>

app/views/endroits/index.html.erb
<h1>Listing endroits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @endroits.each do |endroit| %>
      <tr>
        <td><%= endroit.name %></td>
        <td><%= endroit.url %></td>
        <td><%= link_to 'Show', endroit %></td>
        <td><%= link_to 'Edit', edit_endroit_path(endroit) %></td>
        <td><%= link_to 'Destroy', endroit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endroit', new_endroit_path %>

app/views/endroits/new.html.erb
<h1>New endroit</h1>

<%= render 'form' %>

<%= link_to 'Back', endroits_path %>

app/views/endroits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @endroit.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @endroit.url %>
</p>

<%= link_to 'Edit', edit_endroit_path(@endroit) %> |
<%= link_to 'Back', endroits_path %>

app/views/equipes/_form.html.erb
<%= form_for(@equipe) do |f| %>
  <% if @equipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@equipe.errors.count, "error") %> prohibited this equipe from being saved:</h2>

      <ul>
      <% @equipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :categ_id %><br>
    <%= f.collection_select :categ_id, @categ.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/equipes/edit.html.erb
<h1>Editing equipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @equipe %> |
<%= link_to 'Back', equipes_path %>

app/views/equipes/index.html.erb
<h1>Listing equipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Categ</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @equipes.each do |equipe| %>
      <tr>
        <td><%= equipe.name %></td>
        <td><%= @categs.find(equipe.categ).name %></td>
        <td><%= link_to 'Show', equipe %></td>
        <td><%= link_to 'Edit', edit_equipe_path(equipe) %></td>
        <td><%= link_to 'Destroy', equipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Equipe', new_equipe_path %>

app/views/equipes/new.html.erb
<h1>New equipe</h1>

<%= render 'form' %>

<%= link_to 'Back', equipes_path %>

app/views/equipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @equipe.name %>
</p>

<p>
  <strong>Categ:</strong>
  <%= @categs.find(@equipe.categ).name %>
</p>

<%= link_to 'Edit', edit_equipe_path(@equipe) %> |
<%= link_to 'Back', equipes_path %>

app/views/fetcher/fetch_prices.html.erb
it works
<%= @doc %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Horairehockey</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>